services:
  backend:
    build:
      context: ./backend_v2
      dockerfile: ../Dockerfile.backend
    container_name: backend_v2
    ports:
      - "8080:8080"
    env_file:
      - ./backend_v2/.env